= link:https://svoz.litovle.cz[Svoz odpadu v Litovli i místních částech]

== Proč vznikl web link:https://svoz.litovle.cz[svoz.litovle.cz]

* *Rychlost kdekoliv* +
Vše je minimalistické a velmi rychlé na jekémkoliv zařízení a připojení

* *Přesné informace podle adresy* +
Vybereš ulici, dostaneš kalendář.

* *Reflektuje změny ve svozu* +
Pokud město změní harmonogram (svátky, výluky), kalednář je upraven.

* *Jednoduchost bez zbytečností* +
Nechceš přemýšlet, jestli je zrovna sudý nebo lichý týden.

=== Kiokový mód

Pro zobrazení kalendáře bez ovládacích prvků použijte `kiosk=true` parametr: https://svoz.litovle.cz/?kiosk=true

Kalendář je pak použitelný v různých dashboardech.

== Obsah repozitáře

Velmi jednoduchý a naivní skript pro vygenerování `ics` souborů a `csv` souboru se svozy odpadů pro jednotlivé ulice i místní části.

Soubor `ics` lze importovat do Google kalendáře a pravděpodobně i dalších aplikací. Kalendáře jsou ke stažení ve složce link:calendars/[`calendars`].

Soubor `csv` slouží primárně jako zdroj dat pro link:index.html[index.html] dostupný z https://svoz.litovle.cz

== Lokální build a validace

Projekt používá Python 3.12. Závislosti jsou deklarované v link:requirements.txt[`requirements.txt`].

[source,sh]
----
python -m pip install -r requirements.txt
python scripts/validate_project.py
python scripts/build_site.py --output-dir _site
python scripts/validate_site_artifact.py _site
----

Výsledný deployovatelný web je ve složce `_site/`, která se necommituje. Lokálně ho lze zobrazit například:

[source,sh]
----
python -m http.server --directory _site
----

Původní příkaz `python generator_svozu_odpadu.py` zůstává podporovaný pro aktualizaci trackovaných generated snapshotů v kořeni repozitáře.

=== Co je zdroj a co je generated výstup

Autoritativní zdroj pravidelného harmonogramu je v Pythonu, jednorázové změny jsou v `data/svoz_exceptions.json` a městské podklady jsou v `resources/`.

Repozitář zatím záměrně používá hybridní model:

* trackované generated snapshoty: `index.html`, `ulice/`, `calendars/`, `waste_schedule.csv`, `sitemap.xml`
* ignorované generated výstupy: `_site/` a `resources/social/*.png`

Trackované snapshoty pomáhají při review změn a drží kompatibilitu s notifikacemi do aplikace. Social preview obrázky se necommitují, protože jsou binární a mění se podle aktuálního data; generují se až do deploy artefaktu. URL obrázků používá stabilní název souboru a query parametr `?v=...`, který se změní při změně obsahu obrázku.

Kalendáře v `calendars/` jsou trackované záměrně. Slouží jako validační snapshoty změn svozu a současně jako veřejné soubory pro existující odběry kalendářů. Pro každou lokaci se zatím generují dvě URL varianty: původní název s diakritikou a stabilní slug bez diakritiky. Web používá slug variantu, ale původní názvy zůstávají kvůli zpětné kompatibilitě s už importovanými kalendáři.

== GitHub Actions

GitHub Pages musí být nastavené na nasazování přes GitHub Actions, ne přímo z větve.

Workflowy:

* `CI` běží na pull requestech, pushi do `main` a ručně. Instaluje závislosti, spouští projektovou validaci, sestaví `_site` a validuje artefakt.
* `Deploy generated site` běží po pushi do `main`, ručně a denně v `03:17 UTC`. Sestaví aktuální `_site` a nasadí ho přes GitHub Pages artefakt.
* `Watch Litovel.eu` běží denně v `06:17 UTC` a ručně. Pouze hlásí kandidátní články z webu města, nic nemění.
* `Notify app on change` běží při pushi do `main`, pokud se změní kalendáře nebo zdrojové soubory ovlivňující harmonogram. Posílá FCM refresh do Android aplikace.

=== Přidání změny svozu

1. Ověřit oficiální zdroj a uložit odkaz včetně archivu.
2. Přidat jednorázovou změnu do `data/svoz_exceptions.json`; Python logiku měnit jen pokud změna vyžaduje novou skupinu nebo pravidlo.
3. Spustit `python generator_svozu_odpadu.py`, aby se aktualizovaly trackované snapshoty.
4. Spustit `python scripts/validate_project.py`.
5. Pro kontrolu produkčního artefaktu spustit `python scripts/build_site.py --output-dir _site` a `python scripts/validate_site_artifact.py _site`.

== Import ics do Google kalendáře

=== Včetně synchronizace a notifikace v mobilu

link:docs/synchronizace-notifikace.adoc[Synchronizace/notifikace pro svozy odpadů]

=== Bez synchronizace

https://support.google.com/calendar/answer/37118?hl=cs&co=GENIE.Platform%3DDesktop

== Zdrojová data

Zdrojová data se nachází v link:resources/[resources/]. Jsou to letáčky distribuované městem v PDF podobě. Součástí repozitáře jsou proto, aby byly dohledatelné případné změny.

=== Model svozu

Pravidelný harmonogram svozu zůstává v Pythonu v souboru link:lokace_svozu.py[`lokace_svozu.py`].

Jednorázové změny svozu jsou v link:data/svoz_exceptions.json[`data/svoz_exceptions.json`]. Každá změna má stabilní `id`, typ odpadu, dotčené lokace nebo skupinu lokací, akci a datum změny. Pokud se používá `affected_location_group`, seznam míst může být přiložen jen jako `affected_locations_snapshot`; samostatné `affected_locations` je autoritativní pouze bez skupiny. Objekt `source` musí obsahovat klíče `url` a `title`; krátký doklad z oznámení lze uložit do `source.evidence`.

Budoucí automatizace má upravovat pouze datový soubor s jednorázovými změnami, ne Python logiku pravidelného harmonogramu.

=== Změny svozu

* 2025-12-17 https://www.facebook.com/litovel.eu/posts/pfbid02mx6FiHsbQETRC2V9vzuCBQMpQUDh84tfzyz7NspBdy3AL5pMdApFuzaqmGLwSfphl, https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmeny-svozu-odpadu-o-vanocnich-svatcich.html archiv https://web.archive.org/web/20251217074956/https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Flitovel.eu%2Fposts%2Fpfbid02mx6FiHsbQETRC2V9vzuCBQMpQUDh84tfzyz7NspBdy3AL5pMdApFuzaqmGLwSfphl a https://archive.is/Cuen5
* 2026-02-12 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-odpadu.html, archiv https://archive.is/BOR4n
* 2026-07-02 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-odpadu-v-pondeli-6-cervence.html, archiv https://web.archive.org/web/20260702141618/https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-odpadu-v-pondeli-6-cervence.html
* 2026-07-09 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/svoz-bioodpadu-se-presouva-na-patek-10-7.html, archiv https://web.archive.org/web/20260709140452/https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/svoz-bioodpadu-se-presouva-na-patek-10-7.html

.Archiv 2025
[%collapsible]
====

* 2024-12-18 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-odpadu-v-dobe-vanocnich-svatku.html, archiv https://web.archive.org/web/20241218100710/https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-odpadu-v-dobe-vanocnich-svatku.html
* 2024-12-30 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-bioodpadu-v-mistnich-castech-z-30-12-na-2-1.html, archiv https://web.archive.org/web/20241230151257/https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-bioodpadu-v-mistnich-castech-z-30-12-na-2-1.html
* 2024-12-31? Poznámka: Přidány i Unčovice po dotazu https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-bioodpadu-v-mistnich-castech-z-30-12-na-2-1.html, archiv https://web.archive.org/web/20241231075813/https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-svozu-bioodpadu-v-mistnich-castech-z-30-12-na-2-1.html
* 2025-04-14 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmeny-svozu-odpadu-behem-velikonoc.html, archiv https://archive.is/SpRQH
* 2025-05-07 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmeny-ve-svozu-odpadu-v-mesici-kvetnu.html, archiv https://archive.is/vrQhk
* 2025-05-21 https://www.litovel.eu/cs/urad/uredni-deska/aktualni-informace/zmena-ve-svozu-odpadu.html, archiv https://archive.is/PsJVG
* 2025-07-04 https://www.litovel.eu/redakce/index.php?xuser=234858626223493812&lanG=cs&slozka=47816&xsekce=43561&clanek=374062, archiv https://archive.is/G2KGV a https://archive.is/O5jH7
* 2025-09-09 https://www.facebook.com/litovel.eu/posts/pfbid02af6wuEMQTm3G4xLmkpFG5b8YnTEH2Pk4wSw3oPgbBkovEmRqTb76cfzaDCDs15pFl, archiv https://web.archive.org/web/20250909192642/https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Flitovel.eu%2Fposts%2Fpfbid02af6wuEMQTm3G4xLmkpFG5b8YnTEH2Pk4wSw3oPgbBkovEmRqTb76cfzaDCDs15pFl
* 2025-11-13 https://www.facebook.com/litovel.eu/posts/pfbid02qBuwZJERREtkX7ZMeEmobrmRJLbSXmoqLWbAs7DSuNqN8Q72sDggJxGmGAr7iq46l, archiv https://web.archive.org/web/20251113031217/https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Flitovel.eu%2Fposts%2Fpfbid02qBuwZJERREtkX7ZMeEmobrmRJLbSXmoqLWbAs7DSuNqN8Q72sDggJxGmGAr7iq46l

====

== Licence

The GNU General Public License v3.0 dostupná na https://www.gnu.org/licenses/gpl-3.0.en.html
