all_streets = {
    'Litovel': [
    '1. máje',
    'B. Němcové',
    'Bezručova',
    'Boskovicova',
    'Cholinská',
    'Chořelice',
    'Družstevní',
    'Dukelská',
    'G. Frištenského',
    'Gemerská - rodinné domy',
    'Gemerská - sídliště',
    'Havlíčkova',
    'Hrnčířská',
    'Husova',
    'Javoříčská',
    'Jiráskova',
    'Jungmannova',
    'Karla Sedláka - sídliště',
    'Karlov',
    'Karlovská',
    'Kollárova',
    'Komenského',
    'Komárov',
    'Kosmonautů',
    'Kostelní',
    'Koupaliště',
    'Králova',
    'Kysucká',
    'Lesní zátiší',
    'Lidická',
    'Loštická',
    'Lužní',
    'Masarykova',
    'Mlýnská',
    'Nasobůrská',
    'Novosady - sídliště',
    'Nová',
    'Nábřežní',
    'Nádražní',
    'Nám. Př. Otakara',
    'Olomoucká',
    'Opletalova',
    'Palackého',
    'Pavlínka',
    'Poděbradova',
    'Polní',
    'Pošmýlská',
    'Příčná',
    'Revoluční',
    'Revúcká',
    'Rybníček',
    'Sadová',
    'Severní',
    'Smyčkova',
    'Sochova',
    'Sovova',
    'Staroměstské náměstí',
    'Studentů',
    'Sušilova',
    'Svatoplukova',
    'Tichá',
    'Třebízského',
    'Třídvorská',
    'U Stadionu',
    'Uničovská',
    'Uničovská - sídliště',
    'Vlašímova',
    'Vodní',
    'Vítězná',
    'Wolkerova',
    'Zahradní',
    'nám. Svobody',
    'Vítězná',
    'Vítězná - sídliště',
    'Červenská',
    'Čihadlo',
    'Čs. armády',
    'Šafaříkova',
    'Šargounská',
    'Šemberova',
    'Šerhovní',
    'Šmakalova',
    'Štefánikova',
    'Švermova',
    'Švédská',
    'Žerotínova',
    'Novosady - rodinné domy',
    'Severní - rodinné domy',
    ]
}

mistni_casti = ['Březové', 'Chořelice', 'Chudobín', 'Myslechovice', 'Nasobůrky', 'Nová Ves', 'Unčovice', 'Rozvadovice', 'Savín', 'Tři Dvory', 'Víska']